# Generated by Django 5.2 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='updated_cv')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('personal', 'personal'), ('production', 'production'), ('academic', 'academic')], max_length=75)),
                ('github_link', models.TextField(blank=True, null=True)),
                ('is_deployed', models.BooleanField(default=False)),
                ('deployed_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
