# Generated by Django 5.2 on 2025-04-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='rate',
            field=models.CharField(default='0', max_length=101),
        ),
    ]
